### PR TITLE
fixed all title logos on all pages

### LINKED ISSUE #75: BUG: There is no title logo
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Screenshot 2024-01-07 004428

Wanna add the logo in title bar ! Can u assign me with this issue ?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AbhineshJha**
## Related Issue

Fixes #75

## Description

Fixed title logo on all pages

## Screenshots

Screenshot 2024-01-07 011424

### CODE REVIEW

**Comment by siwamsingh** [comment]
hey @AbhineshJha  well every thing is great can you just edit the logo and make it round 
image
just remove the gray background and crop it in round shape

**Comment by siwamsingh** [comment]
image
the inner circle is the logo you can edit the size of outer circle as you wish

**Comment by siwamsingh** [comment]
plz make the follwing changes as mentioned above

**Comment by AbhineshJha** [comment]
sure sir

**Pull request closed without merging**
