### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by GauriGA**
Changed the hover effect color to blue from grey in the footer section to all the social media icons and the content.

### CODE REVIEW

**Comment by GauriGA** [comment]
@Shaba1406 is there any other changes you would like me to do?

**Comment by Shaba1406** [comment]
Could you please share some ss as well

**Comment by GauriGA** [comment]
@Shaba1406 here is the ss
pic 3
pic 4
pic 1
pic 2

**Comment by Shaba1406** [comment]
Social media hover effects can be more improved

**Comment by Shaba1406** [comment]
@dakshsinghrathore please give ur suggestions on this.

**Comment by GauriGA** [comment]
@Shaba1406 If you want, I can add a transform property to scale the icons on hover for a subtle zoom effect and hover:shadow-md property to add a shadow on hover for depth.

**Review by dakshsinghrathore — APPROVED** [review]
lgtm !

**Comment by dakshsinghrathore** [comment]
@Shaba1406 Kindly assign this PR to @GauriGA and add the apt labels.

**Pull request merged**
