### PR TITLE
feat :Enhanced Home page

### LINKED ISSUE #48: Feat: Improved homepage
### Describe the feature

I Think the homepage looks too plain and I can keep the color theme same and edit it to make it look better. I previously edited the register page for the same site so that's my reference work!

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Yatin12527**
## Related Issue

fixed #48 
## Description

I've incorporated graphics and new background which makes it look more lively.

## Screenshots

**The lag in this recording is due to my low system configuration and due to that it was lagging when i turned on the recorder but ideally the animation of page doesnot stutter and is smooth.**

https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/134225415/c4b72e77-5b13-408f-920c-264a00ac0532

### CODE REVIEW

**Review by dakshsinghrathore — APPROVED** [review]
lgtm !

**Comment by Yatin12527** [comment]
@dakshsinghrathore hey i was wondering about the design seems like u didnot like my approach of putting a video in background .

**Comment by dakshsinghrathore** [comment]
@Yatin12527 wasn't working on deployment so reverted the changes.

**Comment by Yatin12527** [comment]
@dakshsinghrathore oh idk what the issues might have been but i rly liked the background but it is what it is now haha next time maybe.

**Pull request merged**
