### PR TITLE
About Section Added

### PR DESCRIPTION
**Pull request by Manishkr1007**
## Screenshots

Screenshot (108)

### CODE REVIEW

**Comment by siwamsingh** [comment]
well we wanted the about section to be something like this 
https://dribbble.com/shots/22462433-Children-s-school-of-modern-digital-skills
no animation is required and the colors should match our color theme

**Comment by siwamsingh** [comment]
@dakshsinghrathore  check the design i mention . Add if anything is needed

**Comment by Manishkr1007** [comment]
> @dakshsinghrathore check the design i mention . Add if anything is needed

ok  I will work on it

**Comment by Manishkr1007** [comment]
> @dakshsinghrathore check the design i mention . Add if anything is needed

I think it would be the different about page because it tells about the course and As ,I made the about page which is for whole website not for specific course.

**Comment by siwamsingh** [comment]
in the blue part you can add 
organization - brighter beginning 
format  - online
description - "any short description "
opensource - link to github repo

**Comment by Manishkr1007** [comment]
> in the blue part you can add organization - brighter beginning format - online description - "any short description " opensource - link to github repo

ok I will do

**Comment by siwamsingh** [comment]
> > @dakshsinghrathore check the design i mention . Add if anything is needed
> 
> I think it would be the different about page because it tells about the course and As ,I made the about page which is for whole website not for specific course. @siwamsingh

>i mentioned some points which you can use

**Pull request closed without merging**
