### PR TITLE
About Page

### PR DESCRIPTION
**Pull request by bhavya-anand19**
## Related Issue

issue #45  
## Description
Created an about page

## Screenshots

https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/133582773/1beeaba8-a325-4d7a-937a-f9d8c766b399

### CODE REVIEW

**Review by dakshsinghrathore — APPROVED** [review]
LGTM !

**Comment by bhavya-anand19** [comment]
@dakshsinghrathore  Do I need to make more changes?

**Comment by siwamsingh** [comment]
@bhavya-anand19 remove the home button and  add sufficient padding to cards.

**Comment by bhavya-anand19** [comment]
> @bhavya-anand19 remove the home button and add sufficient padding to cards.

Okk

**Pull request closed without merging**
