### PR TITLE
Fix( blog.html)

### PR DESCRIPTION
**Pull request by Ashwin145**
The blog page wasn't working  .So i updated it  and wrote about  some programming languages along with links to external blogs related to each language .

Screenshot (3)
Screenshot (4)
Screenshot (5)
Screenshot (6)
Screenshot (7)

### CODE REVIEW

**Comment by Ashwin145** [comment]
@dakshsinghrathore ??

**Comment by Ashwin145** [comment]
@dakshsinghrathore please Check blog page as well

**Comment by Ashwin145** [comment]
@dakshsinghrathore ??

**Review by dakshsinghrathore — APPROVED** [review]
Looks good to me 🙌🏼

**Pull request merged**
